language: android
android:
  components:
    - platform-tools
    - build-tools-21.1.1
    - android-13
    - extra-android-support
    
jdk: oraclejdk7

notifications:
  email: false

before_install:
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod +x android-ndk-r10e-linux-x86_64.bin && ./android-ndk-r10e-linux-x86_64.bin > /dev/null
  - mv android-ndk-r10e android-ndk
  - export PATH=`pwd`/android-ndk:`pwd`/android-sdk-linux/tools:`pwd`/android-sdk-linux/platform-tools:$PATH
  - git submodule init 
  - git submodule update
script:
  - sh gen-version.sh travis build
  - python2 makepak.py xash-extras assets/extras.pak
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-armv7.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="armeabi"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-armv6.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 SUPPORT_WEBP=false -j2 APP_CFLAGS="-w" APP_ABI="x86"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-x86.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 clean
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 -j2 APP_CFLAGS="-w" APP_ABI="armeabi-v7a-hard" CFLAGS_OPT_ARM="-mthumb -mfpu=vfpv3-d16 -mcpu=cortex-a9 -pipe -fPIC"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-armv7-tegra2.apk
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 clean
  - ndk-build NDK_TOOLCHAIN_VERSION=4.8 XASH_SDL=1 -j2 APP_CFLAGS="-w" APP_ABI="armeabi" CFLAGS_OPT_ARMv5="-marm -march=armv5te -msoft-float -fPIC"
  - ant debug
  - cp bin/xashdroid-debug.apk xashdroid-armv5.apk


after_script:
  - sh scripts/travis-upload.sh

